ugolok/urls.py
from django.contrib import admin
from django.urls import path
from wd import urls as wd_url
from django.urls import include,path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf.urls.static import static
from wd import views as wd_views
from ugolok import settings
from ugolok import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('wd/', include((wd_url,"wd"), namespace='wd')),
    path('', views.index,name = 'main'),
    path('register/', views.sign_up,name = 'sign_up'),
    path('login/',
         LoginView.as_view
         (
             template_name='ugolok/login.html',
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(r'^favicon.ico$', document_root='media/ugolok_logo.png')

wd/urls.py
from django.contrib import admin
from django.urls import path
from wd import views
import requests
from django.conf.urls.static import static
from ugolok import settings
from ugolok import views as uviews
# from wd import url

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('main', views.index, name='index'),
    # path('', uviews.index, name='index'),
    # path('u/', views.user_list, name='user_list'),
    # path('chat/', views.enter, name='chat'),
    # path('<str:room_name>/', views.room, name='room'),
    path('lobby/<int:game_id>/', views.lobby, name='lobby'),
    path('game/<int:game_id>/', views.game, name='game'),
    path('game/<int:game_id>/order/', views.order, name='order'),
    path('game/<int:game_id>/country/', views.country, name='country'),
    path('game/<int:game_id>/orders/', views.orders, name='orders'),
    path('game/<int:game_id>/orders/apply/<int:round_id>/', views.apply_round, name='round_apply'),
    path('game/<int:game_id>/orders/reset/', views.reset, name='reset'),
    path('lobby/create/', views.creategame, name='create'),
    # path('websockets/', views.websockets, name='websockets'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(r'^favicon.ico$', document_root='media/ugolok_logo.png')

ugolok/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from datetime import datetime
from wd.models import *
import requests
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

# Create your views here.
def index(request):
    return render(request,template_name='ugolok/index.html')

class PlayerCreationForm(UserCreationForm):
    class Meta:
        model=Player 
        fields = ('username', 'password1', 'password2')


def sign_up(request):
    form = PlayerCreationForm()
    if request.method == 'POST':
        form = PlayerCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('login'))
        else:
            print(form.errors)
    return render(request, 'ugolok/sign_up.html', {'form': form})

wd/views.py
from django.shortcuts import render
from datetime import datetime
import requests
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import *
from django import forms
from django.core.exceptions import ValidationError

# import React from 'react'

# Create your views here.
def index(request):
    return render(
        request,
        'wd/index.html',
        {
            'title':'Home Page',
            'games':Game.objects.all()
        }
    )

# def user_list(request):
#     return render(request, 'wd/user_list.html')
User = get_user_model()

def enter(request):
    return render(request, 'wd/search_chat.html')

@login_required(login_url='/login/')
def room(request, room_name):
    return render(request, 'wd/room.html', {
        'room_name': room_name
    })

@login_required(login_url='/login/')
def creategame(request):
    game = Game.objects.create(ecology=100,creator_id=request.user)
    return redirect('game',game.id)

@login_required(login_url='/login/')
def lobby(request, game_id):
    game = Game.objects.filter(id=game_id)[0]    
    countries = Country.objects.filter(game=game)
    players = Player.objects.all().exclude(is_superuser=True,is_staff=True)
    list_={}
    for country in countries:
        cities = City.objects.filter(country=country)
        city_list=[]
        for city in cities:
            city_list.append(city)
        list_[country] = city_list
        city_list={}
    if(request.POST):
        cs = Country.objects.all()
        
        for c in cs:
            if(request.POST[c.name] != None or request.POST[c.name] != 'Select one'):
                c.president=Player.objects.filter(id=request.POST[c.name])[0]
                c.save(update_fields=["president"])
    return render(request, 'wd/lobby.html', {
        'game': game,
        'cc':list_,
        'ccs':countries,
        'ps':players,
    })

@login_required(login_url='/login/')
def game(request, game_id):
    game = Game.objects.filter(id=game_id)[0]    
    countries = Country.objects.filter(game=game)
    players = Player.objects.all().exclude(is_superuser=True,is_staff=True)
    rounds = Round.objects.all()
    list_={}
    for country in countries:
        cities = City.objects.filter(country=country)
        city_list=[]
        for city in cities:
            city_list.append(city)
        list_[country] = city_list
        city_list={}
    
    return render(request, 'wd/game.html', {
        'game': game,
        'cc':list_,
        'ccs':countries,
        'rounds':rounds,
        'ps':players,
    })

class OrderForm(forms.ModelForm):
    class Meta:
        model=Order
        fields=('round','country')


def clean_values(obj):
    field = ""
    for value in obj:
      field += str(value)+","
    return field.rstrip(",")

@login_required
def order(request,game_id):
    game = Game.objects.filter(id=game_id)[0]
    rounds = Round.objects.filter(game=game)
    mc = Country.objects.filter(president=request.user)
    if(mc.count()>0):
        ccs = Country.objects.all().exclude(president=request.user)
        cities = City.objects.all().exclude(country=mc[0])

    else:
        return redirect('wd:game',game_id)
    if(request.POST):
        form = OrderForm(request.POST)
        print(form.data)
        print(form.is_valid())
        if(form.is_valid()):
            Order.objects.create(
                country=Country.objects.filter(id=int(form.data['country']))[0],
                round=Round.objects.filter(id=int(form.data['round']))[0],
                status_for_city_1=(form.data.get('status_for_city_1')),
                status_for_city_2=(form.data.get('status_for_city_2')),
                status_for_city_3=(form.data.get('status_for_city_3')),
                status_for_city_4=(form.data.get('status_for_city_4')),
                shield_for_city_1=(form.data.get('shield_for_city_1')),
                shield_for_city_2=(form.data.get('shield_for_city_2')),
                shield_for_city_3=(form.data.get('shield_for_city_3')),
                shield_for_city_4=(form.data.get('shield_for_city_4')),
                build_tech=(form.data.get('build_tech')),
                eco_up=(form.data.get('eco_up')),
                buy_rockets=form.data.get('buy_rockets'),
                rockets_to=clean_values(form.data.getlist('rockets_to')),
                saction_to=clean_values(form.data.getlist('saction_to')),
                order_cost=form.data.get('order_cost')
            )
    else:
        form = OrderForm()

    return render(request, 'wd/order.html', {
        'game': game,
        'rounds':rounds,
        'cs':ccs,
        'cities':cities,
        'mcities':City.objects.all().filter(country=mc[0]),
        'mc':mc[0],
        'form':form
    })

from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

@login_required
def orders(request,game_id):
    if(request.user.id!=1):
        return redirect("wd:game",game_id)
    game = Game.objects.filter(id=game_id)[0]
    rounds = Round.objects.filter(game=game)
    countries = Country.objects.all()
    list_=[]
    list_c={}
    for round in rounds:
        for country in countries:
            orders = Order.objects.filter(round=round,country=country).order_by("-pub_date").first()
            list_c[country]=(orders)
        list_.append(list_c)
        list_c={}
    
    return render(request, 'wd/orders.html', {
        'game': game,
        'rounds':rounds,
        'ro':list_,
    })

def status_calc(cur_,status):
    if(status and cur_>0):
        return cur_+25
    return cur_

@login_required
def apply_round(request,game_id,round_id):
    if(request.user.id!=1):
        return redirect("wd:game",game_id)
    game = Game.objects.filter(id=game_id)[0]
    round_ = Round.objects.filter(id=round_id,game=game)[0]
    countries = Country.objects.all()
    rockets_to_list = {}
    saction_to_list = {}
    list_c=[]
    for country in countries:
        orders = Order.objects.filter(round=round_,country=country).order_by("-pub_date").first()
        list_c.append(orders)
    
    print(list_c)
    for order in list_c:
        if(order!=None):
            country = Country.objects.filter(id=order.country.id).first()
            cities = City.objects.filter(country=country)
            o_l_ = [order.status_for_city_1,order.status_for_city_2,order.status_for_city_3,order.status_for_city_4]
            o_l_2 = [order.shield_for_city_1,order.shield_for_city_2,order.shield_for_city_3,order.shield_for_city_4]
            i = 0
            for city in cities:
                city.update_status(o_l_[i])
                city.shield=o_l_2[i]
                city.save(update_fields=["status","shield"]) 
                i+=1
            if(order.build_tech):
                country.technology = order.build_tech
                if(round_.ecology>0):
                    round_.ecology -= 10
            if(order.buy_rockets>0):
                if(round_.ecology>0):
                    round_.ecology -= 15*order.buy_rockets
            country.rockets += order.buy_rockets
            if(order.eco_up):
                if(round_.ecology<86):
                    round_.ecology += 15
            if(order.rockets_to!=None):
                rockets_to_list[country.id]=order.rockets_to
            if(order.saction_to!=None):
                saction_to_list[country.id]=order.saction_to
            country.budget= country.budget - order.order_cost + (cities[0].status * 3 + cities[1].status * 3 + cities[2].status * 3 + cities[3].status * 3) -  50*round((round_.ecology/10))
                
            country.save(update_fields=["technology","rockets","budget"])   
            round_.save(update_fields=["ecology"])
                
    for k,v in rockets_to_list.items():
        for c_id in v.split(','):
            country = Country.objects.filter(id=k).first()
            city = City.objects.filter(id=c_id).first()
            if(city.shield):
                city.shield = False
                city.status-=30
            else:
                city.status = 0
            country.rockets-=1
            city.save(update_fields=["shield","status"])
            country.save(update_fields=["rockets"])

    for k,v in saction_to_list.items():
        for c_id in v.split(','):
            country_from = Country.objects.filter(id=k).first()
            country_to = Country.objects.filter(id=c_id).first()
            print(country_from,country_to)
            country_to.budget-=round(country_to.budget*0.15)
            country_to.save(update_fields=["budget"])
    
                
                
    return redirect("wd:orders",game_id)


def country(request,game_id):
    game = Game.objects.filter(id=game_id).first()
    c=Country.objects.filter(game=game,president=request.user).first()
    cities = City.objects.filter(country=c)
    rounds = Round.objects.filter(game=game)
    orders = []
    for round_ in rounds:
        orders.append(Order.objects.filter(country=c,round=round_).order_by("-pub_date").first())
    return render(request, 'wd/country.html', {
        'game': game,
        'rounds':rounds,
        'c':c,
        'orders':orders,
        'cities':cities,
    })


def reset(request,game_id):
    if(request.user.id!=1):
        return redirect("wd:game",game_id)
    game = Game.objects.filter(id=game_id).first()
    c=Country.objects.filter(game=game)
    for country in c:
        cities = City.objects.filter(country=country)
        country.budget = 1000
        country.technology = False
        country.rockets = 0
        i = 0
        for city in cities:
            city.shield = False
            if(i == 0):
                city.status = 100

wd/templates/ugolok/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<link rel="icon" href="/media/ugolok_logo.png">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Ugolok</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<style>
    .bs-example{
        margin: 20px;
    }
</style>
</head>
<body>
  <div class="bs-example">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
          <a href="#" class="navbar-brand">
              <img src="media/ugolok_logo.png" height="28" alt="Уголок">
          </a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="{% url 'main' %}" class="nav-item nav-link active">Уголок</a>
                    <a href="https://discord.gg/7VjvDR9" class="nav-item nav-link">Discord ссылка</a>
                    {% comment %} <a href="#" class="nav-item nav-link">Profile</a> {% endcomment %}
                    {% comment %} <a href="#" class="nav-item nav-link">Messages</a> {% endcomment %}
                    {% comment %} <a href="#" class="nav-item nav-link disabled" tabindex="-1">Reports</a> {% endcomment %}
                </div>
                <div class="navbar-nav ml-auto ">
                    {% if user.is_authenticated %}
                        <a href="#" class="nav-item nav-link ">{{user.username}}</a>
                        <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>    
    </div>
    <div class="container">
        <div class="card-group">
            <div class="card">
                <img
                src="/media/wd_screen.jpg"
                class="card-img-top"
                alt="..."
                />
                <div class="card-body">
                <h5 class="card-title">Мировое Господство</h5>
                <p class="card-text">
                    Представь, что ты и твои друзья — группа влиятельных политиков. Под рукой красная кнопка и арсенал ядерных боеголовок, готовых по приказу стереть с лица земли города противников.

По ту сторону экрана — правительства других стран. Это может быть команда друзей или люди, которых вы видите впервые. Чего ждать? Мирного сотрудничества или вероломного нападения? Щедрых инвестиций или подлых экономических санкций? Доверять нельзя никому. Победный статус сверхдержавы достанется только одной команде!

До последнего отстаивать мирные принципы или устроить ядерный апокалипсис на планете? Решение за тобой. В этой игре можно все: вступать в переговоры, торговаться, блефовать и плести интриги или отгородиться железным занавесом и тайком от всех ковать орудие возмездия. Захватывающий микс из классической «Мафии» и пошаговой политической стратегии понравится и тем, кто пришел за фаном, и любителям выстраивать хитрые многоходовочки
                </p>
                </div>
                <div class="card-footer">
                    <a name="" id="" class="btn btn-primary" href="{% url 'wd:index' %}" role="button">Начать</a>
                </div>
            </div>
            <div class="card">
                <img
                src="https://mdbootstrap.com/img/new/standard/city/042.jpg"
                class="card-img-top"
                alt="..."
                />
                <div class="card-body">
                <h5 class="card-title">Игра Престолов</h5>
                <p class="card-text">
                    This card has supporting text below as a natural lead-in to additional content.
                </p>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary disabled" role="button" >Начать</a>
                    
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

wd/templates/ugolok/login.html
<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap Login Form with Avatar Image</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #fff;
	background: #d47677;
}
.form-control {
	min-height: 41px;
	background: #fff;
	box-shadow: none !important;
	border-color: #e3e3e3;
}
.form-control:focus {
	border-color: #70c5c0;
}
.form-control, .btn {        
	border-radius: 2px;
}
.login-form {
	width: 350px;
	margin: 0 auto;
	padding: 100px 0 30px;		
}
.login-form form {
	color: #7a7a7a;
	border-radius: 2px;
	margin-bottom: 15px;
	font-size: 13px;
	background: #ececec;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 30px;	
	position: relative;	
}
.login-form h2 {
	font-size: 22px;
	margin: 35px 0 25px;
}
.login-form .avatar {
	position: absolute;
	margin: 0 auto;
	left: 0;
	right: 0;
	top: -50px;
	width: 95px;
	height: 95px;
	border-radius: 50%;
	z-index: 9;
	background: #70c5c0;
	padding: 15px;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);
}
.login-form .avatar img {
	width: 100%;
}	
.login-form input[type="checkbox"] {
	position: relative;
	top: 1px;
}
.login-form .btn, .login-form .btn:active {        
	font-size: 16px;
	font-weight: bold;
	background: #70c5c0 !important;
	border: none;
	margin-bottom: 20px;
}
.login-form .btn:hover, .login-form .btn:focus {
	background: #50b8b3 !important;
}    
.login-form a {
	color: #fff;
	text-decoration: underline;
}
.login-form a:hover {
	text-decoration: none;
}
.login-form form a {
	color: #7a7a7a;
	text-decoration: none;
}
.login-form form a:hover {
	text-decoration: underline;
}
.login-form .bottom-action {
	font-size: 14px;
}
</style>
</head>
<body>
<div class="login-form">
    <form action="." method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="avatar">
            <img src="/media/ugolok_logo.png" alt="ugolok">
        </div>
        <h2 class="text-center">Member Login</h2>   
        <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Username" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>        
        <div class="form-group">
            <input type="hidden" name="next" value="/" />
            <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>
        </div>
        <div class="bottom-action clearfix">
            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>
            <a href="#" class="float-right">Forgot Password?</a>
        </div>
        {% if form.errors %}
        <p class="validation-summary-errors">Please enter a correct user name and password.</p>
        {% endif %}
    </form>
    <p class="text-center small">Don't have an account? <a href="{% url 'sign_up' %}">Sign up here!</a></p>
</div>

</body></html>

wd/templates/ugolok/sign_up.html
<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap Login Form with Avatar Image</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #fff;
	background: #d47677;
}
.form-control {
	min-height: 41px;
	background: #fff;
	box-shadow: none !important;
	border-color: #e3e3e3;
}
.form-control:focus {
	border-color: #70c5c0;
}
.form-control, .btn {        
	border-radius: 2px;
}
.login-form {
	width: 350px;
	margin: 0 auto;
	padding: 100px 0 30px;		
}
.login-form form {
	color: #7a7a7a;
	border-radius: 2px;
	margin-bottom: 15px;
	font-size: 13px;
	background: #ececec;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 30px;	
	position: relative;	
}
.login-form h2 {
	font-size: 22px;
	margin: 35px 0 25px;
}
.login-form .avatar {
	position: absolute;
	margin: 0 auto;
	left: 0;
	right: 0;
	top: -50px;
	width: 95px;
	height: 95px;
	border-radius: 50%;
	z-index: 9;
	background: #70c5c0;
	padding: 15px;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);
}
.login-form .avatar img {
	width: 100%;
}	
.login-form input[type="checkbox"] {
	position: relative;
	top: 1px;
}
.login-form .btn, .login-form .btn:active {        
	font-size: 16px;
	font-weight: bold;
	background: #70c5c0 !important;
	border: none;
	margin-bottom: 20px;
}
.login-form .btn:hover, .login-form .btn:focus {
	background: #50b8b3 !important;
}    
.login-form a {
	color: #fff;
	text-decoration: underline;
}
.login-form a:hover {
	text-decoration: none;
}
.login-form form a {
	color: #7a7a7a;
	text-decoration: none;
}
.login-form form a:hover {
	text-decoration: underline;
}
.login-form .bottom-action {
	font-size: 14px;
}
</style>
</head>
<body>
<div class="login-form">
    <form action="{% url 'sign_up' %}" method="post">
        {% csrf_token %}
        <div class="form-group ">
            <label for="id_username">Имя пользователя:</label>
            <input type="text" class="form-control" name="username" maxlength="150" autofocus="" required="" id="id_username">
        </div>
        
        <div class="form-group ">
            <label for="id_password1">Пароль:</label>
            <input type="password" class="form-control" name="password1" autocomplete="new-password" required="" id="id_password1">
        </div>
        
        <div class="form-group ">
            <label for="id_password2">Подтверждение пароля:</label>
            <input type="password" class="form-control" name="password2" autocomplete="new-password" required="" id="id_password2">
        </div>
        
        <button type="submit" class="btn btn-primary btn-lg btn-block">Sign up</button>
        <p class="text-center small">Already have an account? <a href="{% url 'login' %}">Log in!</a></p>
    </form>
</div>

</body></html>