ugolok/urls.py
from django.contrib import admin
from django.urls import path
from wd import urls as wd_url
from django.urls import include,path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf.urls.static import static
from wd import views as wd_views
from ugolok import settings
from ugolok import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('wd/', include((wd_url,"wd"), namespace='wd')),
    path('', views.index,name = 'main'),
    path('register/', views.sign_up,name = 'sign_up'),
    path('login/',
         LoginView.as_view
         (
             template_name='ugolok/login.html',
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(r'^favicon.ico$', document_root='media/ugolok_logo.png')

wd/urls.py
from django.contrib import admin
from django.urls import path
from wd import views
import requests
from django.conf.urls.static import static
from ugolok import settings
from ugolok import views as uviews
# from wd import url

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('main', views.index, name='index'),
    # path('', uviews.index, name='index'),
    # path('u/', views.user_list, name='user_list'),
    # path('chat/', views.enter, name='chat'),
    # path('<str:room_name>/', views.room, name='room'),
    path('lobby/<int:game_id>/', views.lobby, name='lobby'),
    path('game/<int:game_id>/', views.game, name='game'),
    path('game/<int:game_id>/order/', views.order, name='order'),
    path('game/<int:game_id>/country/', views.country, name='country'),
    path('game/<int:game_id>/orders/', views.orders, name='orders'),
    path('game/<int:game_id>/orders/apply/<int:round_id>/', views.apply_round, name='round_apply'),
    path('game/<int:game_id>/orders/reset/', views.reset, name='reset'),
    path('lobby/create/', views.creategame, name='create'),
    # path('websockets/', views.websockets, name='websockets'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(r'^favicon.ico$', document_root='media/ugolok_logo.png')

wd/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import AbstractUser,AbstractBaseUser
from django.utils.translation import gettext_lazy as _
import os
from django.core.cache import cache 
from django.contrib.auth.models import Group
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator


class Timer(models.Model):
    game = models.ForeignKey('Game', related_name='gametimer', on_delete=models.CASCADE,blank=True, null=True)
    name = models.CharField(max_length=30,blank=True, null=True)
    status = models.CharField(max_length=5,blank=True, null=True)
    message = models.CharField(max_length=30,blank=True, null=True)
    start_seconds = models.IntegerField(_("start_seconds"),blank=True, null=True)
    seconds_elapsed = models.IntegerField(_("seconds_elapsed"),blank=True, null=True)
    seconds_remaining = models.IntegerField(_("seconds_remaining"),blank=True, null=True)

    def __str__(self):
        return (str(self.start_seconds)+ " - " + str(self.seconds_elapsed) + " = " + str(self.seconds_remaining))

class Room(models.Model):
    name = models.TextField()
    label = models.SlugField(unique=True)

class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    handle = models.TextField()
    message = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)


class Player(AbstractUser):
    status=models.CharField(_("status"), max_length=50,blank=True, null=True)
    email=models.EmailField( max_length=254,blank=True, null=True)
    first_name=None
    last_name=None

class Game(models.Model):
    # ecology = models.IntegerField('Экология',default=100,blank=True, null=True)
    creator_id = models.ForeignKey('Player', related_name='creator', on_delete=models.CASCADE,blank=True, null=True)

class Round(models.Model):
    name = models.CharField(_("Имя Раунда"), max_length=50 ,blank=True, null=True)
    ecology = models.IntegerField('Экология',default=100,blank=True, null=True)
    game = models.ForeignKey('Game', related_name='gameround', on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class Country(models.Model):
    game = models.ForeignKey('Game', related_name='Game', on_delete=models.CASCADE)
    name = models.CharField('ИМЯ СТРАНЫ', max_length=150,blank=True, null=True)
    budget = models.IntegerField('БЮДЖЕТ СТРАНЫ',blank=True, null=True)
    technology = models.BooleanField('Ядерная технология',default=False,blank=True, null=True)
    rockets = models.IntegerField('Количество ракет', default=0, blank=True, null=True)
    president = models.ForeignKey('Player', related_name='Player', on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    

class City(models.Model):
    country = models.ForeignKey('Country', related_name='Country', on_delete=models.CASCADE)
    name = models.CharField('ИМЯ ГОРОДА', max_length=150,blank=True, null=True)
    shield = models.BooleanField('ЩИТ',default=False,blank=True, null=True)
    status = models.IntegerField('СТАТУС',blank=True, null=True)
    def __str__(self):
        return self.name
    def update_status(self,status_):
        if(status_ and self.status>0):
            self.status+=25
    



class Order(models.Model):
    round = models.ForeignKey('Round', related_name='Round', on_delete=models.CASCADE)
    country = models.ForeignKey('Country', related_name='order_for', on_delete=models.CASCADE)
    status_for_city_1 = models.BooleanField(_("статус на город1"),default=False,blank=True, null=True)
    status_for_city_2 = models.BooleanField(_("статус на город2"),default=False,blank=True, null=True)
    status_for_city_3 = models.BooleanField(_("статус на город3"),default=False,blank=True, null=True)
    status_for_city_4 = models.BooleanField(_("статус на город4"),default=False,blank=True, null=True)
    shield_for_city_1 = models.BooleanField(_("щит на город1"),default=False,blank=True, null=True)
    shield_for_city_2 = models.BooleanField(_("щит на город2"),default=False,blank=True, null=True)
    shield_for_city_3 = models.BooleanField(_("щит на город3"),default=False,blank=True, null=True)
    shield_for_city_4 = models.BooleanField(_("щит на город4"),default=False,blank=True, null=True)
    build_tech = models.BooleanField('кач ядерки',default=False,blank=True, null=True)
    buy_rockets = models.IntegerField("покупка ракетт",default=0,blank=True, null=True)
    eco_up = models.BooleanField("Улучшение экологии",default=False,blank=True, null=True)
    rockets_to = models.CharField("Города под прицелом",max_length=254,blank=True, null=True)
    saction_to = models.CharField("Страны для санкции",max_length=254,blank=True, null=True)
    order_cost = models.IntegerField("Стоимость приказа",blank=True, null=True)
    pub_date = models.DateTimeField('Дата отправки приказа',default= timezone.now)
    def __str__(self):
        return "Cost:"+str(self.order_cost)+" Time:"+str(self.pub_date.time().strftime("%H:%M:%S"))
    

wd/views.py
from django.shortcuts import render
from datetime import datetime
import requests
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import *
from django import forms
from django.core.exceptions import ValidationError

# import React from 'react'

# Create your views here.
def index(request):
    return render(
        request,
        'wd/index.html',
        {
            'title':'Home Page',
            'games':Game.objects.all()
        }
    )

# def user_list(request):
#     return render(request, 'wd/user_list.html')
User = get_user_model()

def enter(request):
    return render(request, 'wd/search_chat.html')

@login_required(login_url='/login/')
def room(request, room_name):
    return render(request, 'wd/room.html', {
        'room_name': room_name
    })

@login_required(login_url='/login/')
def creategame(request):
    game = Game.objects.create(ecology=100,creator_id=request.user)
    return redirect('game',game.id)

@login_required(login_url='/login/')
def lobby(request, game_id):
    game = Game.objects.filter(id=game_id)[0]    
    countries = Country.objects.filter(game=game)
    players = Player.objects.all().exclude(is_superuser=True,is_staff=True)
    list_={}
    for country in countries:
        cities = City.objects.filter(country=country)
        city_list=[]
        for city in cities:
            city_list.append(city)
        list_[country] = city_list
        city_list={}
    if(request.POST):
        cs = Country.objects.all()
        
        for c in cs:
            if(request.POST[c.name] != None or request.POST[c.name] != 'Select one'):
                c.president=Player.objects.filter(id=request.POST[c.name])[0]
                c.save(update_fields=["president"])
    return render(request, 'wd/lobby.html', {
        'game': game,
        'cc':list_,
        'ccs':countries,
        'ps':players,
    })

@login_required(login_url='/login/')
def game(request, game_id):
    game = Game.objects.filter(id=game_id)[0]    
    countries = Country.objects.filter(game=game)
    players = Player.objects.all().exclude(is_superuser=True,is_staff=True)
    rounds = Round.objects.all()
    list_={}
    for country in countries:
        cities = City.objects.filter(country=country)
        city_list=[]
        for city in cities:
            city_list.append(city)
        list_[country] = city_list
        city_list={}
    
    return render(request, 'wd/game.html', {
        'game': game,
        'cc':list_,
        'ccs':countries,
        'rounds':rounds,
        'ps':players,
    })

class OrderForm(forms.ModelForm):
    class Meta:
        model=Order
        fields=('round','country')


def clean_values(obj):
    field = ""
    for value in obj:
      field += str(value)+","
    return field.rstrip(",")

@login_required
def order(request,game_id):
    game = Game.objects.filter(id=game_id)[0]
    rounds = Round.objects.filter(game=game)
    mc = Country.objects.filter(president=request.user)
    if(mc.count()>0):
        ccs = Country.objects.all().exclude(president=request.user)
        cities = City.objects.all().exclude(country=mc[0])

    else:
        return redirect('wd:game',game_id)
    if(request.POST):
        form = OrderForm(request.POST)
        print(form.data)
        print(form.is_valid())
        if(form.is_valid()):
            Order.objects.create(
                country=Country.objects.filter(id=int(form.data['country']))[0],
                round=Round.objects.filter(id=int(form.data['round']))[0],
                status_for_city_1=(form.data.get('status_for_city_1')),
                status_for_city_2=(form.data.get('status_for_city_2')),
                status_for_city_3=(form.data.get('status_for_city_3')),
                status_for_city_4=(form.data.get('status_for_city_4')),
                shield_for_city_1=(form.data.get('shield_for_city_1')),
                shield_for_city_2=(form.data.get('shield_for_city_2')),
                shield_for_city_3=(form.data.get('shield_for_city_3')),
                shield_for_city_4=(form.data.get('shield_for_city_4')),
                build_tech=(form.data.get('build_tech')),
                eco_up=(form.data.get('eco_up')),
                buy_rockets=form.data.get('buy_rockets'),
                rockets_to=clean_values(form.data.getlist('rockets_to')),
                saction_to=clean_values(form.data.getlist('saction_to')),
                order_cost=form.data.get('order_cost')
            )
    else:
        form = OrderForm()

    return render(request, 'wd/order.html', {
        'game': game,
        'rounds':rounds,
        'cs':ccs,
        'cities':cities,
        'mcities':City.objects.all().filter(country=mc[0]),
        'mc':mc[0],
        'form':form
    })

from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

@login_required
def orders(request,game_id):
    if(request.user.id!=1):
        return redirect("wd:game",game_id)
    game = Game.objects.filter(id=game_id)[0]
    rounds = Round.objects.filter(game=game)
    countries = Country.objects.all()
    list_=[]
    list_c={}
    for round in rounds:
        for country in countries:
            orders = Order.objects.filter(round=round,country=country).order_by("-pub_date").first()
            list_c[country]=(orders)
        list_.append(list_c)
        list_c={}
    
    return render(request, 'wd/orders.html', {
        'game': game,
        'rounds':rounds,
        'ro':list_,
    })

def status_calc(cur_,status):
    if(status and cur_>0):
        return cur_+25
    return cur_

@login_required
def apply_round(request,game_id,round_id):
    if(request.user.id!=1):
        return redirect("wd:game",game_id)
    game = Game.objects.filter(id=game_id)[0]
    round_ = Round.objects.filter(id=round_id,game=game)[0]
    countries = Country.objects.all()
    rockets_to_list = {}
    saction_to_list = {}
    list_c=[]
    for country in countries:
        orders = Order.objects.filter(round=round_,country=country).order_by("-pub_date").first()
        list_c.append(orders)
    
    print(list_c)
    for order in list_c:
        if(order!=None):
            country = Country.objects.filter(id=order.country.id).first()
            cities = City.objects.filter(country=country)
            o_l_ = [order.status_for_city_1,order.status_for_city_2,order.status_for_city_3,order.status_for_city_4]
            o_l_2 = [order.shield_for_city_1,order.shield_for_city_2,order.shield_for_city_3,order.shield_for_city_4]
            i = 0
            for city in cities:
                city.update_status(o_l_[i])
                city.shield=o_l_2[i]
                city.save(update_fields=["status","shield"]) 
                i+=1
            if(order.build_tech):
                country.technology = order.build_tech
                if(round_.ecology>0):
                    round_.ecology -= 10
            if(order.buy_rockets>0):
                if(round_.ecology>0):
                    round_.ecology -= 15*order.buy_rockets
            country.rockets += order.buy_rockets
            if(order.eco_up):
                if(round_.ecology<86):
                    round_.ecology += 15
            if(order.rockets_to!=None):
                rockets_to_list[country.id]=order.rockets_to
            if(order.saction_to!=None):
                saction_to_list[country.id]=order.saction_to
            country.budget= country.budget - order.order_cost + (cities[0].status * 3 + cities[1].status * 3 + cities[2].status * 3 + cities[3].status * 3) -  50*round((round_.ecology/10))
                
            country.save(update_fields=["technology","rockets","budget"])   
            round_.save(update_fields=["ecology"])
                
    for k,v in rockets_to_list.items():
        for c_id in v.split(','):
            country = Country.objects.filter(id=k).first()
            city = City.objects.filter(id=c_id).first()
            if(city.shield):
                city.shield = False
                city.status-=30
            else:
                city.status = 0
            country.rockets-=1
            city.save(update_fields=["shield","status"])
            country.save(update_fields=["rockets"])

    for k,v in saction_to_list.items():
        for c_id in v.split(','):
            country_from = Country.objects.filter(id=k).first()
            country_to = Country.objects.filter(id=c_id).first()
            print(country_from,country_to)
            country_to.budget-=round(country_to.budget*0.15)
            country_to.save(update_fields=["budget"])
    
                
                
    return redirect("wd:orders",game_id)


def country(request,game_id):
    game = Game.objects.filter(id=game_id).first()
    c=Country.objects.filter(game=game,president=request.user).first()
    cities = City.objects.filter(country=c)
    rounds = Round.objects.filter(game=game)
    orders = []
    for round_ in rounds:
        orders.append(Order.objects.filter(country=c,round=round_).order_by("-pub_date").first())
    return render(request, 'wd/country.html', {
        'game': game,
        'rounds':rounds,
        'c':c,
        'orders':orders,
        'cities':cities,
    })


def reset(request,game_id):
    if(request.user.id!=1):
        return redirect("wd:game",game_id)
    game = Game.objects.filter(id=game_id).first()
    c=Country.objects.filter(game=game)
    for country in c:
        cities = City.objects.filter(country=country)
        country.budget = 1000
        country.technology = False
        country.rockets = 0
        i = 0
        for city in cities:
            city.shield = False
            if(i == 0):
                city.status = 100

wd/templates/wd/index.html
{% extends "wd/layout.html" %} 
{% block content %} 
    <div class="container">
        {% comment %} <a name="" id="" class="btn btn-primary" href="games/create" role="button">создать игру</a> {% endcomment %}
        {% for game in games  %}
            <a name="" id="" class="btn btn-primary" href="{% url 'wd:game' game.id %}" role="button">Зайти в игру №{{game.id}}</a>
            <br />
        {% endfor %}
    </div>
{% endblock %}

wd/templates/wd/order.html
{% extends "wd/layout.html" %} 
{% block content %}
<div class="container">
    {% comment %} {{form.as_p}} {% endcomment %}
</div>
<form action="." method="post" class="form-horizontal">
{% csrf_token %}
<div class="container padding" style="height:1000px">
    <div class="row">
        <h1>Приказ от {{mc}}</h1> 
    </div>
    <div class="row">
        <h5>Доступный бюджет - стоимость приказа: 
        <h5 id="budget">{{mc.budget}} </h5> - <h5 id="total_cost"> 0 </h5> = <h5 id="total_value">1000</h5></h5>
    </div>
    <div class="alert alert-danger d-none" id="cost_alert" role="alert">
        Нехватка денег для отправки приказа!
    </div>
    <div class="alert alert-danger" id="round_alert" role="alert">
        Раунд не выбран!
    </div>
    <div class="row">
        <h5>Доступных ракет: {{mc.rockets}}</h5>
    </div>
    <div class="row" style="height:25px;">
    </div>

    <div class="row justify-content-center">
        <div class="col-md-12">
            <label for="id_round">Раунд:</label>
            {% for r in rounds %}
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="round" id="inlineRadio{{ forloop.counter }}" value="{{r.id}}">
                    <label class="form-check-label" for="inlineRadio{{ forloop.counter }}">{{r.name}}</label>
                </div>
            {% endfor %}
            
            <div class="form-group">
                <label class="sr-only" for="inputName">Hidden input label</label>
                <input type="hidden" class="form-control" name="country" id="id_country" placeholder="" value="{{mc.id}}">
            </div>
            <div class="form-group">
                <label class="sr-only" for="inputName">Hidden input label</label>
                <input type="hidden" class="form-control" name="order_cost" id="id_order_cost" placeholder="" value="0">
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Город:</th>
                        <th>статус(200):</th>
                        <th>щит(300):</th>
                    </tr>
                </thead>
                <tbody>
                {% for city in mcities %}
                    <tr>
                        <td scope="row">{{city.name}}</td>
                        <td>
                        <div class="d-flex justify-content-sm-between w-25">
                            {{city.status}}%
                            <input type="checkbox" name="status_for_city_{{ forloop.counter }}" value="True" id="id_status_for_city_{{ forloop.counter }}">
                        </div>
                        </td>
                        <td>
                        <div class="d-flex justify-content-sm-between w-25">
                            {% if city.shield == True  %}
                            Есть
                            {% else %}
                            Нет
                            {% endif %}
                            <input type="checkbox" name="shield_for_city_{{ forloop.counter }}" value="True" id="id_shield_for_city_{{ forloop.counter }}">

                        </div>
                        </td>
                    </tr>
                {% endfor %}  
                </tbody>
            </table>
            <div class="form-check form-check-inline">
                <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" name="eco_up" value="True"  id="id_eco_up"> Изучение экологии (200)
                </label>
            </div>
            <div class="form-check form-check-inline">
                <label class="form-check-label">
                {% if mc.technology == False %} 
                    <input class="form-check-input" type="checkbox" name="build_tech" id="id_build_tech" value="True"> Изучить ядерную технологию(500)
                {% else %}
                    Ядерная технология Изучена!
                {% endif %}
                </label>
            </div>
            <div class="form-group">
                <label for="">Создать ядерное оружие (250):</label>
                {% if mc.technology == False %} 
                    <div class="alert alert-primary" role="alert">
                        <strong>Ядерная технология не Изучена!</strong>
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="id_buy_rockets">Hidden input label</label>
                        <input type="hidden" class="form-control" name="buy_rockets" id="id_buy_rockets" placeholder="" value="0">
                    </div>
                    
                {% else %}
                {% if mc.rockets > 0 %}
                    <select class="form-control" name="buy_rockets" id="id_buy_rockets">
                        <option value="0" selected="">0</option>
                        <option value="1" >1</option>
                        <option value="2" >2</option>
                        <option value="3" >3</option>
                    </select>
                {% else %}
                Нет доступных ракет
                {% endif %}
                
                {% endif %}
            </div>
            
            <p><label>Отправить ракету на города:</label> </p><ul id="id_rockets_to">
            {% if mc.rockets > 0 %}
                {% for city in cities %}
                    <li>
                    <label for="id_rockets_to_{{city.id}}"><input type="checkbox" name="rockets_to" value="{{city.id}}" id="id_rockets_to_{{city.id}}">
                        {{city.country}}|{{city.name}}
                    </label>
                    </li>
                {% endfor %}
            {% else %}
                Нет доступных ракет
            {% endif %}

            </li>
            </ul><p></p>
            <p><label>Cанкции для стран(250):</label> </p>
            <ul id="id_saction_to">
                {% for c in cs %}
                    <li>
                    <label for="id_providers_{{ forloop.counter0 }}"><input type="checkbox" name="saction_to" value="{{c.id}}" id="id_saction_to_0">
                        {{c.name}}
                    </label>
                </li>
                {% endfor %}
            </ul>
            <p></p>
        </div>

    </div>
    
        <button type="submit" class="btn btn-primary btn-lg">Отправить приказ</button>

</div>
</form>

<script>

{% comment %} asd = document.getElementsByTagName('input');
list_ = []

function check_all_in_document(doc)
{
   var arr = new Array();
   arr = document.getElementsByTagName('input');

   for (var i = 0; i < arr.length; i++)
   {
       if (arr[i].type == 'checkbox')
       {
           arr[i].checked = true;
       }
   }
} {% endcomment %}

a = document.querySelector("#budget")
b = document.querySelector("#total_cost")
c = document.querySelector("#total_value")
var objs = [
    document.querySelector("#id_status_for_city_1"),
    document.querySelector("#id_status_for_city_2"),
    document.querySelector("#id_status_for_city_3"),
    document.querySelector("#id_status_for_city_4"),
    document.querySelector("#id_eco_up")
    ];
var objs2 = [
    document.querySelector("#id_shield_for_city_1"),
    document.querySelector("#id_shield_for_city_2"),
    document.querySelector("#id_shield_for_city_3"),
    document.querySelector("#id_shield_for_city_4")
]
var obj_2 = document.querySelector("#id_build_tech")
var obj_3 = document.querySelector("#id_buy_rockets")
var obj_4 = document.getElementsByName("saction_to")

var dict = {
    obj_2:500,
    obj_3:250,
    objs2:300,
    objs:200,
};

{% comment %} let summ = 0;

for(let i in objs){
    
}
for (i = 0; i < objs.length; i++) {
  if(objs[i].checked){
        summ+=200
    }
}

summ+=obj_2.checked?500:0
summ+=obj_3.checked?250:0

for (i = 0; i < obj_4.length; i++) {
  if(obj_4[i].checked){
        summ+=300
    }
} {% endcomment %}
{% comment %} console.log(summ) {% endcomment %}
{% comment %} b.innerHTML = summ {% endcomment %}



function calc2(){
    summ = parseInt(b.innerHTML)
    if(this.checked){
        if(this.id=="id_build_tech"){
            summ+=500
        }
        else if(this.name=="saction_to"){
            summ+=250
        }
        else{
            if(this.id=="id_shield_for_city_1"||this.id=="id_shield_for_city_2"||this.id=="id_shield_for_city_3"||this.id=="id_shield_for_city_4"){
                summ+=300
                
            }
            else{
                summ+=200;
                this.parentElement.childNodes[0].textContent=(parseInt(this.parentElement.childNodes[0].textContent.split('%')[0]) + 25)+"%"
            }
        }
    }
    else{
        if(this.id=="id_build_tech"){
            summ-=500
        }
        else if(this.name=="saction_to"){
            summ-=250
        }
        else{
            if(this.id=="id_shield_for_city_1"||this.id=="id_shield_for_city_2"||this.id=="id_shield_for_city_3"||this.id=="id_shield_for_city_4"){
                summ-=300
            }
            else{
                summ-=200;
                this.parentElement.childNodes[0].textContent=(parseInt(this.parentElement.childNodes[0].textContent.split('%')[0]) - 25)+"%"
            }
        }
    }

    b.innerHTML = summ;
    c.innerHTML = parseInt(a.innerHTML) - parseInt(b.innerHTML);
    if(c.innerHTML<0){
        document.querySelector("body > form > div > button").disabled = true
        document.querySelector("#cost_alert").className = "alert alert-danger";
        document.querySelector("body > form > div > button").className = "btn btn-danger btn-lg"
    }
    else{
        document.querySelector("body > form > div > button").disabled = false
        document.querySelector("#cost_alert").className = "alert alert-danger d-none";
        document.querySelector("body > form > div > button").className = "btn btn-primary btn-lg"
    }
    document.querySelector("#id_order_cost").value = b.innerHTML;
};

{% comment %} object.addEventListener("click", myScript); {% endcomment %}
for (i = 0; i < objs.length; i++) {
    objs[i].addEventListener("click", calc2);
}
for (i = 0; i < objs2.length; i++) {
    objs2[i].addEventListener("click", calc2);
}
for (i = 0; i < obj_4.length; i++) {
    obj_4[i].addEventListener("click", calc2);
}
obj_2.addEventListener("click", calc2);
var rs=document.getElementsByName("round")
for (i = 0; i < rs.length; i++) {
    rs[i].addEventListener("click", function(){
        document.querySelector("#round_alert").className = "alert alert-danger d-none";

    });
}
</script>
{% endblock %}

wd/templates/wd/orders.html
{% extends "wd/layout.html" %} 
{% block content %}
    {% comment %} {{ro}} {% endcomment %}
    <div class="container">
    
    <table class="table table-striped table-inverse table-responsive">
        <thead class="thead-inverse">
            <tr>
                <th>Round №</th>
                <th>США:</th>
                <th>Китай:</th> 
                <th>Россия:</th> 
                <th>Иран:</th> 
                <th>Cев. Корея:</th>
                <th>Германия:</th>
                <th>Действие:</th>
            </tr>
            </thead>
            <tbody>
            {% for round in ro %}
                
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                {% for c,o in round.items %}
                    <td>{{o}}</td>
                {% endfor %}
                    <td><a name="" id="" class="btn btn-warning" href="apply/{{ forloop.counter }}" role="button">Применить</a></td>

                </tr>

            {% endfor %}
            </tbody>
    </table>
                    <a name="" id="" class="btn btn-danger" href="{% url 'wd:reset' game.id %}" role="button">Перезапустить</a>
    </div>
    
{% endblock %}

wd/templates/wd/room.html
<!-- chat/templates/chat/room.html -->
{% extends "wd/layout.html" %} 
{% block content %} 
{% comment %} {{user.username}} {% endcomment %}
<div class="container">
    <textarea id="chat-log" cols="100" rows="20" disabled></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
</div>
    
    <script>
        {% comment %} let stopped = false; {% endcomment %}
        {% comment %} const roomName = JSON.parse(document.getElementById('room-name').textContent); {% endcomment %}
        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
        var chat_socket = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + "/chat" + window.location.pathname);
        
        $('#chatform').on('submit', function(event) {
            var message = {
                handle: $('#handle').val(),
                message: $('#message').val(),
            }
            chat_socket.send(JSON.stringify(message));
            return false;
        });

        chatsock.onmessage = function(message) {
            var data = JSON.parse(message.data);
            $('#chat').append('<tr>' 
                + '<td>' + data.timestamp + '</td>' 
                + '<td>' + data.handle + '</td>'
                + '<td>' + data.message + ' </td>'
            + '</tr>');
        };
        
    </script>
{% endblock %}